development:
      host: localhost
      adapter: mysql
      database: schol_dev
      port: 3306
      username: root
      password: hetalksinme2

test: &test
      host: localhost
      adapter: mysql
      database: schol_test
      port: 3306
      username: root
      password: hetalksinme2

production:
      host: localhost
      adapter: mysql
      database: schol_prod
      port: 3306
      username: root
      password: hetalksinme2
cucumber:
  <<: *test
